/*
MIT License

Copyright (c) 2025 mpax235

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

#include "../../info/include/defines.h"
#include "../../info/include/server_info.h"

#ifndef HTTP_RESPONSE_ELEMENTS_H
#define HTTP_RESPONSE_ELEMENTS_H

static char mpax235_301_page[] =
"<!DOCTYPE html>\n"
"<html>\n"
"    <head>\n"
"        <title>301 Moved Permanently</title>\n"
"        <style>\n"
"            @import url('https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap');\n"
"\n"
"            body {\n"
"                background-color: black;\n"
"                margin: 10px;\n"
"                padding: 0;\n"
"                color: #00ffff;\n"
"                font-family: 'Montserrat';\n"
"            }\n"
"\n"
"            h1 {\n"
"                font-weight: normal;\n"
"            }\n"
"\n"
"            hr {\n"
"                border: 1px solid #00ffff;\n"
"            }\n"
"        </style>\n"
"    </head>\n"
"    <body>\n"
"        <center><h1>301 Moved Permanently</h1><center>\n";

static char mpax235_302_page[] =
"<!DOCTYPE html>\n"
"<html>\n"
"    <head>\n"
"        <title>302 Found</title>\n"
"        <style>\n"
"            @import url('https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap');\n"
"\n"
"            body {\n"
"                background-color: black;\n"
"                margin: 10px;\n"
"                padding: 0;\n"
"                color: #00ffff;\n"
"                font-family: 'Montserrat';\n"
"            }\n"
"\n"
"            h1 {\n"
"                font-weight: normal;\n"
"            }\n"
"\n"
"            hr {\n"
"                border: 1px solid #00ffff;\n"
"            }\n"
"        </style>\n"
"    </head>\n"
"    <body>\n"
"        <center><h1>302 Found</h1><center>\n";

static char mpax235_303_page[] =
"<!DOCTYPE html>\n"
"<html>\n"
"    <head>\n"
"        <title>303 See Other</title>\n"
"        <style>\n"
"            @import url('https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap');\n"
"\n"
"            body {\n"
"                background-color: black;\n"
"                margin: 10px;\n"
"                padding: 0;\n"
"                color: #00ffff;\n"
"                font-family: 'Montserrat';\n"
"            }\n"
"\n"
"            h1 {\n"
"                font-weight: normal;\n"
"            }\n"
"\n"
"            hr {\n"
"                border: 1px solid #00ffff;\n"
"            }\n"
"        </style>\n"
"    </head>\n"
"    <body>\n"
"        <center><h1>303 See Other</h1><center>\n";

static char mpax235_307_page[] =
"<!DOCTYPE html>\n"
"<html>\n"
"    <head>\n"
"        <title>307 Temporary Redirect</title>\n"
"        <style>\n"
"            @import url('https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap');\n"
"\n"
"            body {\n"
"                background-color: black;\n"
"                margin: 10px;\n"
"                padding: 0;\n"
"                color: #00ffff;\n"
"                font-family: 'Montserrat';\n"
"            }\n"
"\n"
"            h1 {\n"
"                font-weight: normal;\n"
"            }\n"
"\n"
"            hr {\n"
"                border: 1px solid #00ffff;\n"
"            }\n"
"        </style>\n"
"    </head>\n"
"    <body>\n"
"        <center><h1>307 Temporary Redirect</h1><center>\n";

static char mpax235_308_page[] =
"<!DOCTYPE html>\n"
"<html>\n"
"    <head>\n"
"        <title>308 Permanent Redirect</title>\n"
"        <style>\n"
"            @import url('https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap');\n"
"\n"
"            body {\n"
"                background-color: black;\n"
"                margin: 10px;\n"
"                padding: 0;\n"
"                color: #00ffff;\n"
"                font-family: 'Montserrat';\n"
"            }\n"
"\n"
"            h1 {\n"
"                font-weight: normal;\n"
"            }\n"
"\n"
"            hr {\n"
"                border: 1px solid #00ffff;\n"
"            }\n"
"        </style>\n"
"    </head>\n"
"    <body>\n"
"        <center><h1>308 Permanent Redirect</h1><center>\n";

static char mpax235_400_page[] =
"<!DOCTYPE html>\n"
"<html>\n"
"    <head>\n"
"        <title>400 Bad Request</title>\n"
"        <style>\n"
"            @import url('https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap');\n"
"\n"
"            body {\n"
"                background-color: black;\n"
"                margin: 10px;\n"
"                padding: 0;\n"
"                color: #00ffff;\n"
"                font-family: 'Montserrat';\n"
"            }\n"
"\n"
"            h1 {\n"
"                font-weight: normal;\n"
"            }\n"
"\n"
"            hr {\n"
"                border: 1px solid #00ffff;\n"
"            }\n"
"        </style>\n"
"    </head>\n"
"    <body>\n"
"        <center><h1>400 Bad Request</h1><center>\n";

static char mpax235_401_page[] =
"<!DOCTYPE html>\n"
"<html>\n"
"    <head>\n"
"        <title>401 Unauthorized</title>\n"
"        <style>\n"
"            @import url('https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap');\n"
"\n"
"            body {\n"
"                background-color: black;\n"
"                margin: 10px;\n"
"                padding: 0;\n"
"                color: #00ffff;\n"
"                font-family: 'Montserrat';\n"
"            }\n"
"\n"
"            h1 {\n"
"                font-weight: normal;\n"
"            }\n"
"\n"
"            hr {\n"
"                border: 1px solid #00ffff;\n"
"            }\n"
"        </style>\n"
"    </head>\n"
"    <body>\n"
"        <center><h1>401 Unauthorized</h1><center>\n";

static char mpax235_402_page[] =
"<!DOCTYPE html>\n"
"<html>\n"
"    <head>\n"
"        <title>402 Payment Required</title>\n"
"        <style>\n"
"            @import url('https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap');\n"
"\n"
"            body {\n"
"                background-color: black;\n"
"                margin: 10px;\n"
"                padding: 0;\n"
"                color: #00ffff;\n"
"                font-family: 'Montserrat';\n"
"            }\n"
"\n"
"            h1 {\n"
"                font-weight: normal;\n"
"            }\n"
"\n"
"            hr {\n"
"                border: 1px solid #00ffff;\n"
"            }\n"
"        </style>\n"
"    </head>\n"
"    <body>\n"
"        <center><h1>402 Payment Required</h1><center>\n";

static char mpax235_403_page[] =
"<!DOCTYPE html>\n"
"<html>\n"
"    <head>\n"
"        <title>403 Forbidden</title>\n"
"        <style>\n"
"            @import url('https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap');\n"
"\n"
"            body {\n"
"                background-color: black;\n"
"                margin: 10px;\n"
"                padding: 0;\n"
"                color: #00ffff;\n"
"                font-family: 'Montserrat';\n"
"            }\n"
"\n"
"            h1 {\n"
"                font-weight: normal;\n"
"            }\n"
"\n"
"            hr {\n"
"                border: 1px solid #00ffff;\n"
"            }\n"
"        </style>\n"
"    </head>\n"
"    <body>\n"
"        <center><h1>403 Forbidden</h1><center>\n";

static char mpax235_404_page[] =
"<!DOCTYPE html>\n"
"<html>\n"
"    <head>\n"
"        <title>404 Not Found</title>\n"
"        <style>\n"
"            @import url('https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap');\n"
"\n"
"            body {\n"
"                background-color: black;\n"
"                margin: 10px;\n"
"                padding: 0;\n"
"                color: #00ffff;\n"
"                font-family: 'Montserrat';\n"
"            }\n"
"\n"
"            h1 {\n"
"                font-weight: normal;\n"
"            }\n"
"\n"
"            hr {\n"
"                border: 1px solid #00ffff;\n"
"            }\n"
"        </style>\n"
"    </head>\n"
"    <body>\n"
"        <center><h1>404 Not Found</h1><center>\n";

static char mpax235_405_page[] =
"<!DOCTYPE html>\n"
"<html>\n"
"    <head>\n"
"        <title>405 Method Not Allowed</title>\n"
"        <style>\n"
"            @import url('https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap');\n"
"\n"
"            body {\n"
"                background-color: black;\n"
"                margin: 10px;\n"
"                padding: 0;\n"
"                color: #00ffff;\n"
"                font-family: 'Montserrat';\n"
"            }\n"
"\n"
"            h1 {\n"
"                font-weight: normal;\n"
"            }\n"
"\n"
"            hr {\n"
"                border: 1px solid #00ffff;\n"
"            }\n"
"        </style>\n"
"    </head>\n"
"    <body>\n"
"        <center><h1>405 Method Not Allowed</h1><center>\n";

static char mpax235_406_page[] =
"<!DOCTYPE html>\n"
"<html>\n"
"    <head>\n"
"        <title>406 Not Acceptable</title>\n"
"        <style>\n"
"            @import url('https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap');\n"
"\n"
"            body {\n"
"                background-color: black;\n"
"                margin: 10px;\n"
"                padding: 0;\n"
"                color: #00ffff;\n"
"                font-family: 'Montserrat';\n"
"            }\n"
"\n"
"            h1 {\n"
"                font-weight: normal;\n"
"            }\n"
"\n"
"            hr {\n"
"                border: 1px solid #00ffff;\n"
"            }\n"
"        </style>\n"
"    </head>\n"
"    <body>\n"
"        <center><h1>406 Not Acceptable</h1><center>\n";

static char mpax235_408_page[] =
"<!DOCTYPE html>\n"
"<html>\n"
"    <head>\n"
"        <title>408 Request Timeout</title>\n"
"        <style>\n"
"            @import url('https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap');\n"
"\n"
"            body {\n"
"                background-color: black;\n"
"                margin: 10px;\n"
"                padding: 0;\n"
"                color: #00ffff;\n"
"                font-family: 'Montserrat';\n"
"            }\n"
"\n"
"            h1 {\n"
"                font-weight: normal;\n"
"            }\n"
"\n"
"            hr {\n"
"                border: 1px solid #00ffff;\n"
"            }\n"
"        </style>\n"
"    </head>\n"
"    <body>\n"
"        <center><h1>408 Request Timeout</h1><center>\n";

static char mpax235_409_page[] =
"<!DOCTYPE html>\n"
"<html>\n"
"    <head>\n"
"        <title>409 Conflict</title>\n"
"        <style>\n"
"            @import url('https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap');\n"
"\n"
"            body {\n"
"                background-color: black;\n"
"                margin: 10px;\n"
"                padding: 0;\n"
"                color: #00ffff;\n"
"                font-family: 'Montserrat';\n"
"            }\n"
"\n"
"            h1 {\n"
"                font-weight: normal;\n"
"            }\n"
"\n"
"            hr {\n"
"                border: 1px solid #00ffff;\n"
"            }\n"
"        </style>\n"
"    </head>\n"
"    <body>\n"
"        <center><h1>409 Conflict</h1><center>\n";

static char mpax235_410_page[] =
"<!DOCTYPE html>\n"
"<html>\n"
"    <head>\n"
"        <title>410 Gone</title>\n"
"        <style>\n"
"            @import url('https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap');\n"
"\n"
"            body {\n"
"                background-color: black;\n"
"                margin: 10px;\n"
"                padding: 0;\n"
"                color: #00ffff;\n"
"                font-family: 'Montserrat';\n"
"            }\n"
"\n"
"            h1 {\n"
"                font-weight: normal;\n"
"            }\n"
"\n"
"            hr {\n"
"                border: 1px solid #00ffff;\n"
"            }\n"
"        </style>\n"
"    </head>\n"
"    <body>\n"
"        <center><h1>410 Gone</h1><center>\n";

static char mpax235_411_page[] =
"<!DOCTYPE html>\n"
"<html>\n"
"    <head>\n"
"        <title>411 Length Required</title>\n"
"        <style>\n"
"            @import url('https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap');\n"
"\n"
"            body {\n"
"                background-color: black;\n"
"                margin: 10px;\n"
"                padding: 0;\n"
"                color: #00ffff;\n"
"                font-family: 'Montserrat';\n"
"            }\n"
"\n"
"            h1 {\n"
"                font-weight: normal;\n"
"            }\n"
"\n"
"            hr {\n"
"                border: 1px solid #00ffff;\n"
"            }\n"
"        </style>\n"
"    </head>\n"
"    <body>\n"
"        <center><h1>411 Length Required</h1><center>\n";

static char mpax235_412_page[] =
"<!DOCTYPE html>\n"
"<html>\n"
"    <head>\n"
"        <title>412 Precondition Failed</title>\n"
"        <style>\n"
"            @import url('https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap');\n"
"\n"
"            body {\n"
"                background-color: black;\n"
"                margin: 10px;\n"
"                padding: 0;\n"
"                color: #00ffff;\n"
"                font-family: 'Montserrat';\n"
"            }\n"
"\n"
"            h1 {\n"
"                font-weight: normal;\n"
"            }\n"
"\n"
"            hr {\n"
"                border: 1px solid #00ffff;\n"
"            }\n"
"        </style>\n"
"    </head>\n"
"    <body>\n"
"        <center><h1>412 Precondition Failed</h1><center>\n";

static char mpax235_413_page[] =
"<!DOCTYPE html>\n"
"<html>\n"
"    <head>\n"
"        <title>413 Content Too Large</title>\n"
"        <style>\n"
"            @import url('https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap');\n"
"\n"
"            body {\n"
"                background-color: black;\n"
"                margin: 10px;\n"
"                padding: 0;\n"
"                color: #00ffff;\n"
"                font-family: 'Montserrat';\n"
"            }\n"
"\n"
"            h1 {\n"
"                font-weight: normal;\n"
"            }\n"
"\n"
"            hr {\n"
"                border: 1px solid #00ffff;\n"
"            }\n"
"        </style>\n"
"    </head>\n"
"    <body>\n"
"        <center><h1>413 Content Too Large</h1><center>\n";

static char mpax235_414_page[] =
"<!DOCTYPE html>\n"
"<html>\n"
"    <head>\n"
"        <title>414 URI Too Long</title>\n"
"        <style>\n"
"            @import url('https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap');\n"
"\n"
"            body {\n"
"                background-color: black;\n"
"                margin: 10px;\n"
"                padding: 0;\n"
"                color: #00ffff;\n"
"                font-family: 'Montserrat';\n"
"            }\n"
"\n"
"            h1 {\n"
"                font-weight: normal;\n"
"            }\n"
"\n"
"            hr {\n"
"                border: 1px solid #00ffff;\n"
"            }\n"
"        </style>\n"
"    </head>\n"
"    <body>\n"
"        <center><h1>414 URI Too Long</h1><center>\n";

static char mpax235_415_page[] =
"<!DOCTYPE html>\n"
"<html>\n"
"    <head>\n"
"        <title>415 Unsupported Media Type</title>\n"
"        <style>\n"
"            @import url('https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap');\n"
"\n"
"            body {\n"
"                background-color: black;\n"
"                margin: 10px;\n"
"                padding: 0;\n"
"                color: #00ffff;\n"
"                font-family: 'Montserrat';\n"
"            }\n"
"\n"
"            h1 {\n"
"                font-weight: normal;\n"
"            }\n"
"\n"
"            hr {\n"
"                border: 1px solid #00ffff;\n"
"            }\n"
"        </style>\n"
"    </head>\n"
"    <body>\n"
"        <center><h1>415 Unsupported Media Type</h1><center>\n";

static char mpax235_416_page[] =
"<!DOCTYPE html>\n"
"<html>\n"
"    <head>\n"
"        <title>416 Range Not Satisfiable</title>\n"
"        <style>\n"
"            @import url('https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap');\n"
"\n"
"            body {\n"
"                background-color: black;\n"
"                margin: 10px;\n"
"                padding: 0;\n"
"                color: #00ffff;\n"
"                font-family: 'Montserrat';\n"
"            }\n"
"\n"
"            h1 {\n"
"                font-weight: normal;\n"
"            }\n"
"\n"
"            hr {\n"
"                border: 1px solid #00ffff;\n"
"            }\n"
"        </style>\n"
"    </head>\n"
"    <body>\n"
"        <center><h1>416 Range Not Satisfiable</h1><center>\n";

static char mpax235_421_page[] =
"<!DOCTYPE html>\n"
"<html>\n"
"    <head>\n"
"        <title>421 Misdirected Request</title>\n"
"        <style>\n"
"            @import url('https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap');\n"
"\n"
"            body {\n"
"                background-color: black;\n"
"                margin: 10px;\n"
"                padding: 0;\n"
"                color: #00ffff;\n"
"                font-family: 'Montserrat';\n"
"            }\n"
"\n"
"            h1 {\n"
"                font-weight: normal;\n"
"            }\n"
"\n"
"            hr {\n"
"                border: 1px solid #00ffff;\n"
"            }\n"
"        </style>\n"
"    </head>\n"
"    <body>\n"
"        <center><h1>421 Misdirected Request</h1><center>\n";

static char mpax235_429_page[] =
"<!DOCTYPE html>\n"
"<html>\n"
"    <head>\n"
"        <title>429 Too Many Requests</title>\n"
"        <style>\n"
"            @import url('https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap');\n"
"\n"
"            body {\n"
"                background-color: black;\n"
"                margin: 10px;\n"
"                padding: 0;\n"
"                color: #00ffff;\n"
"                font-family: 'Montserrat';\n"
"            }\n"
"\n"
"            h1 {\n"
"                font-weight: normal;\n"
"            }\n"
"\n"
"            hr {\n"
"                border: 1px solid #00ffff;\n"
"            }\n"
"        </style>\n"
"    </head>\n"
"    <body>\n"
"        <center><h1>429 Too Many Requests</h1><center>\n";

static char mpax235_494_page[] =
"<!DOCTYPE html>\n"
"<html>\n"
"    <head>\n"
"        <title>406 Path Traversal attack blocked</title>\n"
"        <style>\n"
"            @import url('https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap');\n"
"\n"
"            body {\n"
"                background-color: black;\n"
"                margin: 10px;\n"
"                padding: 0;\n"
"                color: #00ffff;\n"
"                font-family: 'Montserrat';\n"
"            }\n"
"\n"
"            h1 {\n"
"                font-weight: normal;\n"
"            }\n"
"\n"
"            hr {\n"
"                border: 1px solid #00ffff;\n"
"            }\n"
"        </style>\n"
"    </head>\n"
"    <body>\n"
"        <center><h1>406 Not Acceptable</h1><center>"
"        <center>Path Traversal attack blocked</center>\n";

static char mpax235_500_page[] =
"<!DOCTYPE html>\n"
"<html>\n"
"    <head>\n"
"        <title>500 Internal Server Error</title>\n"
"        <style>\n"
"            @import url('https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap');\n"
"\n"
"            body {\n"
"                background-color: black;\n"
"                margin: 10px;\n"
"                padding: 0;\n"
"                color: #00ffff;\n"
"                font-family: 'Montserrat';\n"
"            }\n"
"\n"
"            h1 {\n"
"                font-weight: normal;\n"
"            }\n"
"\n"
"            hr {\n"
"                border: 1px solid #00ffff;\n"
"            }\n"
"        </style>\n"
"    </head>\n"
"    <body>\n"
"        <center><h1>500 Internal Server Error</h1><center>\n";

static char mpax235_501_page[] =
"<!DOCTYPE html>\n"
"<html>\n"
"    <head>\n"
"        <title>501 Not Implementedr</title>\n"
"        <style>\n"
"            @import url('https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap');\n"
"\n"
"            body {\n"
"                background-color: black;\n"
"                margin: 10px;\n"
"                padding: 0;\n"
"                color: #00ffff;\n"
"                font-family: 'Montserrat';\n"
"            }\n"
"\n"
"            h1 {\n"
"                font-weight: normal;\n"
"            }\n"
"\n"
"            hr {\n"
"                border: 1px solid #00ffff;\n"
"            }\n"
"        </style>\n"
"    </head>\n"
"    <body>\n"
"        <center><h1>501 Not Implemented</h1><center>\n";

static char mpax235_502_page[] =
"<!DOCTYPE html>\n"
"<html>\n"
"    <head>\n"
"        <title>502 Bad Gateway</title>\n"
"        <style>\n"
"            @import url('https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap');\n"
"\n"
"            body {\n"
"                background-color: black;\n"
"                margin: 10px;\n"
"                padding: 0;\n"
"                color: #00ffff;\n"
"                font-family: 'Montserrat';\n"
"            }\n"
"\n"
"            h1 {\n"
"                font-weight: normal;\n"
"            }\n"
"\n"
"            hr {\n"
"                border: 1px solid #00ffff;\n"
"            }\n"
"        </style>\n"
"    </head>\n"
"    <body>\n"
"        <center><h1>502 Bad Gateway</h1><center>\n";

static char mpax235_503_page[] =
"<!DOCTYPE html>\n"
"<html>\n"
"    <head>\n"
"        <title>503 Service Unavailable</title>\n"
"        <style>\n"
"            @import url('https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap');\n"
"\n"
"            body {\n"
"                background-color: black;\n"
"                margin: 10px;\n"
"                padding: 0;\n"
"                color: #00ffff;\n"
"                font-family: 'Montserrat';\n"
"            }\n"
"\n"
"            h1 {\n"
"                font-weight: normal;\n"
"            }\n"
"\n"
"            hr {\n"
"                border: 1px solid #00ffff;\n"
"            }\n"
"        </style>\n"
"    </head>\n"
"    <body>\n"
"        <center><h1>503 Service Unavailable</h1><center>\n";

static char mpax235_504_page[] =
"<!DOCTYPE html>\n"
"<html>\n"
"    <head>\n"
"        <title>504 Gateway Timeout</title>\n"
"        <style>\n"
"            @import url('https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap');\n"
"\n"
"            body {\n"
"                background-color: black;\n"
"                margin: 10px;\n"
"                padding: 0;\n"
"                color: #00ffff;\n"
"                font-family: 'Montserrat';\n"
"            }\n"
"\n"
"            h1 {\n"
"                font-weight: normal;\n"
"            }\n"
"\n"
"            hr {\n"
"                border: 1px solid #00ffff;\n"
"            }\n"
"        </style>\n"
"    </head>\n"
"    <body>\n"
"        <center><h1>504 Gateway Timeout</h1><center>\n";

static char mpax235_505_page[] =
"<!DOCTYPE html>\n"
"<html>\n"
"    <head>\n"
"        <title>505 HTTP Version Not Supported</title>\n"
"        <style>\n"
"            @import url('https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap');\n"
"\n"
"            body {\n"
"                background-color: black;\n"
"                margin: 10px;\n"
"                padding: 0;\n"
"                color: #00ffff;\n"
"                font-family: 'Montserrat';\n"
"            }\n"
"\n"
"            h1 {\n"
"                font-weight: normal;\n"
"            }\n"
"\n"
"            hr {\n"
"                border: 1px solid #00ffff;\n"
"            }\n"
"        </style>\n"
"    </head>\n"
"    <body>\n"
"        <center><h1>505 HTTP Version Not Supported</h1><center>\n";

static char mpax235_507_page[] =
"<!DOCTYPE html>\n"
"<html>\n"
"    <head>\n"
"        <title>507 Insufficient Storage</title>\n"
"        <style>\n"
"            @import url('https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap');\n"
"\n"
"            body {\n"
"                background-color: black;\n"
"                margin: 10px;\n"
"                padding: 0;\n"
"                color: #00ffff;\n"
"                font-family: 'Montserrat';\n"
"            }\n"
"\n"
"            h1 {\n"
"                font-weight: normal;\n"
"            }\n"
"\n"
"            hr {\n"
"                border: 1px solid #00ffff;\n"
"            }\n"
"        </style>\n"
"    </head>\n"
"    <body>\n"
"        <center><h1>507 Insufficient Storage</h1><center>\n";

#ifdef BUILD
#ifdef _WIN32
std::string footer = 
    "        <hr><center><span>mpax235 WS/build " + std::to_string(buildVersion) + " (Windows)</span></center>\n"
    "    </body>\n"
    "</html>\n";
#else
std::string footer = 
    "        <hr><center><span>mpax235 WS/build " + std::to_string(buildVersion) + " (Linux)</span></center>\n"
    "    </body>\n"
    "</html>\n";
#endif
#else
#ifdef _WIN32
std::string footer = 
    "        <hr><center><span>mpax235 WS/" + releaseVersion + " (Windows)</span></center>\n"
    "    </body>\n"
    "</html>\n";
#else
std::string footer = 
    "        <hr><center><span>mpax235 WS/" + releaseVersion + " (Linux)</span></center>\n"
    "    </body>\n"
    "</html>\n";
#endif
#endif

static char footerNoVersionTag[] =
"        <hr><center><span>mpax23 WS</span></center>\n"
"    </body>\n"
"</html>\n";

static char padding[] =
"<!-- a padding in order to disable friendly error page -->\n";

#endif // HTTP_RESPONSE_ELEMENTS_H